version: 0.0
os: linux
files:
  - source: /frontend
    destination: /home/bitnami/apps/react/htdocs
  - source: /backend
    destination: /home/bitnami/FLASKAPPS/backend
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
