version: 0.0
os: linux
files:
  - source: /frontend
    destination: /home/bitnami/apps/react/htdocs
  - source: /backend
    destination: /home/bitnami/FLASKAPPS/backend
hooks:
  BeforeInstall:
    - location: scripts/cleanup
      timeout: 300
      runas: root
