version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - cp -a $CODEBUILD_SRC_DIR_S3SourceArtifact ./config/

  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - mkdir ./fullbuild
      - cp -a ./build ./fullbuild/frontend
      - cp -a ./backend ./fullbuild/backend 
      - cp ./appspec.yml ./fullbuild/appspec.yml
      - cp -a ./scripts ./fullbuild/scripts
      - cp -a ./apache ./fullbuild/apache
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: fullbuild
